name: cbt_inbal

description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0-266.0.dev

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.7.0
  url_launcher: ^6.3.0
  flutter_widget_from_html_core: ^0.15.2
  flutter_riverpod: ^2.5.1
  http: ^1.2.2
  shared_preferences: ^2.3.2
  get_it: ^8.0.0
  hooks_riverpod: ^2.5.2
  flutter_hooks: ^0.20.5
  logging: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSansHebrew-Regular.ttf
        - asset: assets/fonts/NotoSansHebrew-Bold.ttf
          weight: 700

    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf
        - asset: assets/fonts/Rubik-Bold.ttf
          weight: 700

    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700




























  #


